config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Requests
  # GET / => requests#index
  root to: 'requests#index'
  # get 'requests', to: 'requests#index'
  # # GET /requests/:id = >requests#show
  # get 'requests/:id', to: 'requests#show', id: /\d+/, as: 'request'
  resources 'requests', only: %i[index show]

  # Pokemons
  # Get all pokemons
  resources 'pokemons', only: %i[index show]

  # Pokemonnest
  resources 'pokemonnests', only: %i[index show]

  # Generate all 7 RESTful routes:
  resources :pages

  get ':permalink', to: 'pages#permalink', as: 'permalink'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/pokemon.rb
# frozen_string_literal: true

class Pokemon < ApplicationRecord
  belongs_to :pokemonnest

  has_many :pokemonwaveds
  has_many :requests, through: :pokemonwaves

  validates :name, :move, presence: true
end

app/models/pokemonnest.rb
# frozen_string_literal: true

class Pokemonnest < ApplicationRecord
  has_one :pokemon

  validates :historicalName, :streetName, :streetNumber, :grade, :locationAddress, :constructionDate, presence: true
end

app/models/pokemonwave.rb
# frozen_string_literal: true

class Pokemonwave < ApplicationRecord
  belongs_to :request
  belongs_to :pokemon

  has_many :pokemons
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  has_one :pokemonwave
  has_many :pokemons, through: :pokemonwaves
  validates :date, :serviceArea, :serviceRequest, :longitude, :latitude, :neighbourhood, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  http_basic_authenticate_with name: 'test', password: 'test', except: :peremalink
  before_action :set_page, only: %i[show edit update destroy]

  def permalink
    @page = Page.find_by(permalink: params[:permalink])

    redirect_to root_path if @page.nil?
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/pokemonnests_controller.rb
# frozen_string_literal: true

class PokemonnestsController < ApplicationController
  def index
    @nests = Pokemonnest.all
  end

  def show
    @nest = Pokemonnest.find(params[:id])
  end
end

app/controllers/pokemons_controller.rb
# frozen_string_literal: true

class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @nest = Pokemonnest.find(@pokemon.pokemonnest_id)
  end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < ApplicationController
  def index
    @requests = Request.all.page(params[:page]).per(10)
  end
  # Rails automatically loads the associated view:
  # app/views/request/index.html.erb

  def show
    @request = Request.find(params[:id])
    @pokemons = Pokemonwave.where(request_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemonnests_helper.rb
module PokemonnestsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonIncidentReport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <style>


    </style>
  </head>
    <body>
      <section class="section">
        <div class="container">
          <header>
          <h1 class="title is-1">311 Pokemon service request system</h1>
            <div class="buttons">
              <button class="button is-dark" $button-text-color:$white><%= link_to 'Home', root_path%></button>
              <button class="button is-dark"><%= link_to 'Pokemons', pokemons_path%></button>
              <button class="button is-dark"><%= link_to 'Pokemon nests', pokemonnests_path%></button>
              <button class="button is-dark"><%= link_to 'About Us', permalink_path('about_us')%></button>
            </div>
          </header>
          <%= yield %>
          <footer>
            Pokemon coffee right.
          </footer>
        </div>
      </section>
    </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<h2 class ="subtitle is-2"><%=@page.title%></h2>
<article>
  <%=@page.content%>
</article>
<p>Last updated : <%= @page.updated_at%></p>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pokemonnests/index.html.erb
<h2 class ="subtitle is-2">List of pokemon nest</h2>
<%if @nests.empty?%>
  <p>There are no monsters for the request.</p>
<%else%>
    <div class="columns">
        <%@nests.each do |nest|%>
          <div class="column">
            <div class="box">
              <h3><%=link_to nest.historicalName, nest%></h3>
            </div>
        </div>
        <% end %>
      </div>
<%end%>

app/views/pokemonnests/show.html.erb
<h2>Pokemon Next</h2>
<h2><%= @nest.historicalName%></h2>
<h4>streetName: <%= @nest.streetName%></h4>
<h4>streetNumber: <%= @nest.streetNumber%></h4>
<h4>grade: <%= @nest.grade%></h4>
<h4>constructionDate: <%= @nest.constructionDate%></h4>
<h4>Host pokemon: <%= link_to @nest.pokemon.name,  @nest.pokemon%></h4>

  <div id="map"></div>
  <script>
    var map;
    var marker;
    var myLatLng = {lat: parseFloat("<%=@nest.latitude%>"), lng: parseFloat("<%=@nest.longitude%>")}
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: parseFloat("<%=@nest.latitude%>"), lng: parseFloat("<%=@nest.longitude%>")},
        zoom: 16
      });
      marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Incident here!'
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?AIzaSyDxWX88W5DMaeTsp7T44PmiB4Su3z336fk&callback=initMap"
  async defer></script>

app/views/pokemons/index.html.erb
<h2 class ="subtitle is-2">List of pokemon</h2>
<% if @pokemons.empty?%>
  <p>There are no requests available.</p>
<%else%>
  <div class="columns">
    <%@pokemons.each do |pokemon|%>
    <div class="column">
      <div class="box">
        <h2><%= link_to pokemon.name, pokemon %></h2>
        <img src=<%=pokemon.imageLink%> style="width:60px;height:60px;">
      </div>
    </div>
    <% end %>
  </div>
<%end%>

app/views/pokemons/show.html.erb
<h2>Name : <%=@pokemon.name%></h2>
<h4>Skill: <%=@pokemon.move%></h4>
<h5>Belongs to :<%=link_to @nest.historicalName, @nest%></h5>

app/views/requests/index.html.erb
<h2 class ="subtitle is-2">List of request</h2>
<% if @requests.empty?%>
  <p>There are no requests available.</p>
<%else%>
<p><%=paginate @requests%></p>
  <%@requests.each do |request|%>
    <div class = "box">
      <button class="button is-light"><%= link_to request.serviceRequest, request %></button>
      <div class="content">
        <h4>Department :<%= request.serviceArea%></h4>
        <h4><%= request.date %></h4>
      </div>
    </div>
  <% end %>
<p><%=paginate @requests%></p>
<%end%>

app/views/requests/show.html.erb
<h2><%= @request.serviceRequest %></h2>
<h4>Department :<%= @request.serviceArea%></h4>
<h4><%= @request.date %></h4>

<h3>List of pokemons in this wave</h3>
<%if @pokemons.empty?%>
  <p>There are no monsters for the request.</p>
<%else%>
  <div class ="columns">
      <%@pokemons.each do |pokemon|%>
      <div class="column">
        <div class="box">
          <p><%=link_to pokemon.pokemon.name, pokemon.pokemon%></p>
          <img src=<%=pokemon.pokemon.imageLink%> style="width:60px;height:60px;">
        </div>
      </div>
      <% end %>
  </div>
<%end%>

  <div id="map"></div>
  <script>
    var map;
    var marker;
    var myLatLng = {lat: parseFloat("<%=@request.latitude%>"), lng: parseFloat("<%=@request.longitude%>")}
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: parseFloat("<%=@request.latitude%>"), lng: parseFloat("<%=@request.longitude%>")},
        zoom: 16
      });
      marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Incident here!'
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?AIzaSyDxWX88W5DMaeTsp7T44PmiB4Su3z336fk&callback=initMap"
  async defer></script>